# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gmagick"
    webp:
        generate: false

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        thumb:
            format: jpeg
            quality: 80
            filters:
                fixed:
                    width: 120
                    height: 120
            post_processors:
                jpegoptim: { strip_all: true, max: 80, progressive: true }
        thumb_webp:
            format: webp
            quality: 100
            filters:
                fixed:
                    width: 120
                    height: 120
            post_processors:
                cwebp: { metadata: ["none"], q: 70 }

        image_jpg:
            format: jpeg
            quality: 80
            filters:
                thumbnail:
                    size: [600, 800]
                    mode: inbound
            post_processors:
                jpegoptim: { strip_all: true, max: 80, progressive: true }

        image_webp:
            format: webp
            quality: 100
            filters:
                thumbnail:
                    size: [600, 800]
                    mode: inbound
            post_processors:
                cwebp: { metadata: ["none"], q: 70 }
        image_small_jpg:
            format: jpeg
            quality: 80
            filters:
                thumbnail:
                    size: [400, 600]
                    mode: inbound
            post_processors:
                jpegoptim: { strip_all: true, max: 80, progressive: true }

        image_small_webp:
            format: webp
            quality: 100
            filters:
                thumbnail:
                    size: [400, 600]
                    mode: inbound
            post_processors:
                cwebp: { metadata: ["none"], q: 70 }
        image_middle_jpg:
            format: jpeg
            quality: 80
            filters:
                thumbnail:
                    size: [546, 819]
                    mode: inbound
            post_processors:
                jpegoptim: { strip_all: true, max: 80, progressive: true }

        image_middle_webp:
            format: webp
            quality: 100
            filters:
                thumbnail:
                    size: [546, 819]
                    mode: inbound
            post_processors:
                cwebp: { metadata: ["none"], q: 70 }