framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            liip_imagine:
                dsn: 'doctrine://default?queue_name=liip_imagine'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Liip\ImagineBundle\Message\WarmupCache: liip_imagine
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

when@test:
  framework:
    messenger:
      transports:
        liip_imagine:
          dsn: 'test://'