services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  db:
    driver: local
