name: Build and Deploy
on:
  push:
    branches:
      -   master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
           php-version: "8.3"
           tools: composer, phpcs, phpstan
           coverage: none

      - name: Check PSR12 code style (PHP_CodeSniffer)
        run: phpcs --standard=PSR12 -n src


      # Composer
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: export APP_ENV=prod && composer install --no-dev --no-progress --no-suggest --prefer-dist --optimize-autoloader

      # https://github.com/phpstan/phpstan
      - name: Analyse PHP Code (PHPStan)
        run: phpstan analyse src

      - name: Cache node_modules
        uses: actions/cache@v4
        id: yarn-cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-node-modules-

      - name: Yarn install
        if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Yarn build
        run: yarn run encore production

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public/build